apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: nginx-emptydir #emptydir-volume 共享卷目录 /var/log/nginx
    image: nginx:1.7.1
    ports:
    - containerPort: 80
    volumeMounts: #将emptydir-volume挂在到nginx容器中，对应的目录为 /var/log/nginx  ,nginx的日志文件将保持在emptydir-volume中，
    - name: emptydir-volume
      mountPath: /var/log/nginx #
  - name: busybox-emptydir   # emptydir-volume 共享卷目录 /logs/
    image: busybox:latest
    command: ["/bin/sh","-c","tail -f /logs/access.log"] # 初始命令，动态读取指定文件中内容
    volumeMounts:
    - name: emptydir-volume
      mountPath: /logs
  volumes:
  - name: emptydir-volume # 共享卷
    emptyDir: { 
    }