apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    app: svc
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
