apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-po
  template:
    metadata:
      name: nginx-po
      labels:
        app: nginx-po
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9 # 指定容器的镜像
        imagePullPolicy: IfNotPresent # 镜像拉取策略，指定如果本地有就用本地的，如果没有就拉取远程的
        command: # 指定容器启动时执行的命令
        - nginx
        - -g
        - 'daemon off;' # nginx -g 'daemon off;'
        workingDir: /usr/share/nginx/html # 定义容器启动后的工作目录  

        ports:
        - name: http # 端口名称
          containerPort: 80 # 描述容器内要暴露什么端口
          protocol: TCP # 描述该端口是基于哪种协议通信的
        
        env: # 环境变量
        - name: JVM_OPTS # 环境变量名称
          value: '-Xms128m -Xmx128m' # 环境变量的值
        
        resources:
          requests: # 最少需要多少资源
            cpu: 100m # 限制 cpu 最少使用 0.1 个核心
            memory: 128Mi # 限制内存最少使用 128兆
          limits: # 最多可以用多少资源
            cpu: 200m # 限制 cpu 最多使用 0.2 个核心
            memory: 256Mi # 限制 最多使用 256兆
      
      restartPolicy: Always # 重启策略，只有失败的情况才会重启