apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b0a789f918bedc355f9e3a5dfda1dcf88b8dcb56085df2fd4db024c66e4989a0
    cni.projectcalico.org/podIP: 10.244.36.91/32
    cni.projectcalico.org/podIPs: 10.244.36.91/32
  creationTimestamp: "2023-08-31T08:42:38Z"
  generateName: nginx-rs-
  labels:
    app: nginx-po
  name: nginx-rs-bmjrq
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-rs
    uid: 0a09cb88-7cb4-45e9-8407-0193d0cb3a1f
  resourceVersion: "136821"
  uid: 85723994-c99c-41ff-a163-f97d9f3f5bea
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    env:
    - name: JVM_OPTS
      value: -Xms128m -Xmx128m
    image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-q849x
      readOnly: true
    workingDir: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-node1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-q849x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-31T08:42:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-31T08:43:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-31T08:43:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-31T08:42:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://56e5d1f6f2de00c658ed7a4225fff0474075c57fb99990c6961c06878d846eb5
    image: nginx:1.7.9
    imageID: docker-pullable://nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-31T08:43:22Z"
  hostIP: 192.168.136.12
  phase: Running
  podIP: 10.244.36.91
  podIPs:
  - ip: 10.244.36.91
  qosClass: Burstable
  startTime: "2023-08-31T08:42:39Z"
