apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"nginx-rs","tier":"frontend"},"name":"nginx-rs","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx-po"}},"template":{"metadata":{"labels":{"app":"nginx-po"},"name":"nginx-po"},"spec":{"containers":[{"command":["nginx","-g","daemon off;"],"env":[{"name":"JVM_OPTS","value":"-Xms128m -Xmx128m"}],"image":"nginx:1.7.9","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"workingDir":"/usr/share/nginx/html"}],"restartPolicy":"Always"}}}}
  creationTimestamp: "2023-08-31T08:42:37Z"
  generation: 1
  labels:
    app: nginx-rs
    tier: frontend
  name: nginx-rs
  namespace: default
  resourceVersion: "136849"
  uid: 0a09cb88-7cb4-45e9-8407-0193d0cb3a1f
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-po
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-po
      name: nginx-po
    spec:
      containers:
      - command:
        - nginx
        - -g
        - daemon off;
        env:
        - name: JVM_OPTS
          value: -Xms128m -Xmx128m
        image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /usr/share/nginx/html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
