apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx:1.7.1
    volumeMounts:
      - name: secret-volumes #关联volumes
        mountPath: /etc/secret-volume #指定目录
  volumes: 
    - name: secret-volumes
      secret:
        secretName: test-secret #关联secret
