apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ingress
  namespace: ingress-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-ingress
  template:
    metadata:
      labels:
        app: pod-ingress
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
