apiVersion: v1
kind: Service
metadata:
  name: service-ingress
  namespace: ingress-test
spec:
  selector:
    app: pod-ingress
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
