apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: hostpath-volume
      mountPath: /var/log/nginx
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh","-c","sleep 500"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /logs
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /root/logs  #持久化目录
      type: DirectoryOrCreate #不存在则创建