apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  type: ClusterIP # 指定服务类型
  #clusterIP: 10.97.97.97 # service的ip地址，如果不写，默认会生成一个
  selector:
    app: test #关联pod
  ports: #关联service端口与pod端口
    - name: http  # service 端口配置的名称
      protocol: TCP # 端口绑定的协议，支持 TCP、UDP、SCTP，默认为 TCP
      port: 80 # service端口
      targetPort: 80 # pod端口
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
